# Generated by Django 4.0 on 2022-12-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0002_alter_congregation_congregation_id'),
        ('posts', '0006_post_bookmarks_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregations.congregation'),
        ),
    ]
