# Generated by Django 4.0 on 2022-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_post_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_post_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
