# Generated by Django 4.0 on 2022-12-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0003_congregation_friday_location_and_more'),
        ('profiles', '0003_userprofile_comment_post_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregations.servicegroup'),
        ),
    ]
