# Generated by Django 4.1.7 on 2023-05-17 04:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="17162080698", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
