# Generated by Django 4.1.7 on 2023-05-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="call_id",
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
