# Generated by Django 4.1.7 on 2023-05-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_call_call_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="call",
            name="gender",
            field=models.CharField(
                choices=[("1", "Male"), ("2", "Female")], default=1, max_length=10
            ),
            preserve_default=False,
        ),
    ]
