# Generated by Django 4.1.7 on 2023-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_call_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="gender",
            field=models.CharField(
                choices=[("1", "Male"), ("2", "Female")], default="1", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="returnvisit",
            name="contact_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
