# Generated by Django 4.1.7 on 2023-05-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congregations', '0007_servicemeeting_service_location'),
        ('service', '0005_alter_call_gender_alter_returnvisit_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('1', 'Completed'), ('2', 'Signed Out')], default='1', max_length=20)),
                ('signed_out', models.DateField(blank=True, null=True)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('map', models.FileField(upload_to='')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregations.congregation')),
            ],
        ),
    ]
