# Generated by Django 4.1.9 on 2023-05-19 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_alter_call_age_territory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territory",
            name="map",
            field=models.FileField(
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
