# Generated by Django 4.0 on 2022-11-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='congregation_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
