# Generated by Django 4.0 on 2022-12-16 18:07

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('congregations', '0002_alter_congregation_congregation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='friday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday_service', to='address.address'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='monday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_service', to='address.address'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='saturday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday_service', to='address.address'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='sunday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_service', to='address.address'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='thursday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday_service', to='address.address'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='tuesday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday_service', to='address.address'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='wednesday_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday_service', to='address.address'),
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregations.congregation')),
                ('service_location', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
