# Generated by Django 4.0 on 2022-12-31 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0004_servicegroup_service_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregation',
            name='friday_location',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='monday_location',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='saturday_location',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='sunday_location',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='thursday_location',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='tuesday_location',
        ),
        migrations.RemoveField(
            model_name='congregation',
            name='wednesday_location',
        ),
    ]
