# Generated by Django 4.0 on 2022-12-31 02:00

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('congregations', '0006_servicemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemeeting',
            name='service_location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
