# Generated by Django 4.1.9 on 2023-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0007_servicemeeting_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemeeting',
            name='zoom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemeeting',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicemeeting',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
