# Generated by Django 4.1.9 on 2023-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0008_servicemeeting_zoom_servicemeeting_zoom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemeeting',
            name='zoom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
