# Generated by Django 4.1.9 on 2023-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congregations", "0009_alter_servicemeeting_zoom"),
    ]

    operations = [
        migrations.AddField(
            model_name="congregation",
            name="justacart_token",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
