# Generated by Django 4.0 on 2022-11-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_regularserviceday_day_schedulerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerequest',
            name='request_id',
            field=models.CharField(default=1111111111111111, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='notes',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
