# Generated by Django 4.0 on 2022-11-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedulerequest_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerequest',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('1', 'No'), ('2', 'Yes')], default='1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='confirmation_notes',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
