# Generated by Django 4.0 on 2022-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_schedulerequest_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerequest',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('1', 'No'), ('2', 'Yes')], max_length=5, null=True),
        ),
    ]
