# Generated by Django 4.0 on 2022-12-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0004_servicegroup_service_group_id'),
        ('schedules', '0005_alter_schedulerequest_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularserviceday',
            name='congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregations.congregation'),
        ),
    ]
