# Generated by Django 4.0 on 2022-11-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congregations', '0002_alter_congregation_congregation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('congregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregations.congregation')),
            ],
        ),
    ]
