# Generated by Django 4.0 on 2022-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='name',
            field=models.CharField(default='Name', max_length=254),
            preserve_default=False,
        ),
    ]
