# Generated by Django 4.0 on 2022-12-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0003_congregation_friday_location_and_more'),
        ('invites', '0002_invite_email_invite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregations.servicegroup'),
        ),
    ]
