# Generated by Django 4.0 on 2022-11-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('info', models.TextField(max_length=1024)),
                ('status', models.CharField(blank=True, choices=[('1', 'Unread'), ('2', 'Read')], default='1', max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('1', 'Schedule Request'), ('2', 'Post Like'), ('3', 'Post Comment')], default='1', max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
