# Generated by Django 4.0 on 2022-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Schedule Request'), ('2', 'Post Like'), ('3', 'Post Comment')], max_length=25, null=True),
        ),
    ]
